# This rule is not used by the project mediawiki-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to mediawiki.sng.wiki resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mediawiki-operator
    app.kubernetes.io/managed-by: kustomize
  name: wiki-viewer-role
rules:
- apiGroups:
  - mediawiki.sng.wiki
  resources:
  - wikis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mediawiki.sng.wiki
  resources:
  - wikis/status
  verbs:
  - get
