# This rule is not used by the project mediawiki-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the mediawiki.sng.wiki.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mediawiki-operator
    app.kubernetes.io/managed-by: kustomize
  name: wiki-editor-role
rules:
- apiGroups:
  - mediawiki.sng.wiki
  resources:
  - wikis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mediawiki.sng.wiki
  resources:
  - wikis/status
  verbs:
  - get
